version: "3"
services:
  zookeeper:
    container_name: zookeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  identity:
    container_name: identity
    build: ./packages/identity
    ports:
      - 8080:8080
    volumes:
      - ./packages/identity:/app
    environment:
      - PORT=8080
      - POSTGRES_URL=postgres://postgres:postgres@localhost:5432/postgres
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=topic1
    depends_on:
      - postgres
      - kafka
  others:
    container_name: others
    build: ./packages/others
    ports:
      - 8081:8081
    volumes:
      - ./packages/others:/app
    environment:
      - PORT=8081
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=topic1
    depends_on:
      - kafka
  # products:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./products
  #   container_name: products
  #   ports:
  #     - "8002:8002"
  #   restart: always
  #   depends_on:
  #     - "nosql-db"
  #   volumes:
  #     - .:/app
  #     - /app/products/node_modules

  #   env_file:
  #     - ./products/.env.dev
  # shopping:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./shopping
  #   container_name: shopping
  #   ports:
  #     - "8003:8003"
  #   restart: always
  #   depends_on:
  #     - "nosql-db"
  #   volumes:
  #     - .:/app
  #     - /app/shopping/node_modules
  #   env_file:
  #     - ./shopping/.env.dev
  # customer:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./customer
  #   container_name: customer
  #   ports:
  #     - "8001:8001"
  #   restart: always
  #   depends_on:
  #     - "nosql-db"

  #   volumes:
  #     - .:/app/
  #     - /app/customer/node_modules
  #   env_file:
  #     - ./customer/.env.dev
